// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson357eeadeDecodeGitlabComG6834Team17AnalyticsServiceInternalAdaptersHttp(in *jlexer.Lexer, out *jwtPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "authorized":
			out.Authorized = bool(in.Bool())
		case "user_id":
			out.UserID = string(in.String())
		case "username":
			out.UserName = string(in.String())
		case "first_name":
			out.FirstName = string(in.String())
		case "last_name":
			out.LastName = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "expired":
			out.Expires = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson357eeadeEncodeGitlabComG6834Team17AnalyticsServiceInternalAdaptersHttp(out *jwriter.Writer, in jwtPayload) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Authorized {
		const prefix string = ",\"authorized\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.Authorized))
	}
	if in.UserID != "" {
		const prefix string = ",\"user_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UserID))
	}
	if in.UserName != "" {
		const prefix string = ",\"username\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UserName))
	}
	if in.FirstName != "" {
		const prefix string = ",\"first_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FirstName))
	}
	if in.LastName != "" {
		const prefix string = ",\"last_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LastName))
	}
	if in.Email != "" {
		const prefix string = ",\"email\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Email))
	}
	if in.Expires != 0 {
		const prefix string = ",\"expired\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Expires))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jwtPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson357eeadeEncodeGitlabComG6834Team17AnalyticsServiceInternalAdaptersHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jwtPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson357eeadeEncodeGitlabComG6834Team17AnalyticsServiceInternalAdaptersHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jwtPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson357eeadeDecodeGitlabComG6834Team17AnalyticsServiceInternalAdaptersHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jwtPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson357eeadeDecodeGitlabComG6834Team17AnalyticsServiceInternalAdaptersHttp(l, v)
}
