project:
  name: analytics
  debug: true
  environment: development
  version: 0.1

database:
  type: postgres
  host: localhost
  port: 5432
  user: go_user
  password: 8246go
  db_name: events

rest:
  host: 0.0.0.0
  port: 8080
  debug_port: 8081
  documentation_port: 8082
  gracefulTimeout: 30 # Seconds

grpc:
  host: 0.0.0.0
  port: 5051
  connection_timeout: 10

consumer:
  type: kafka
  brokers: [localhost:9095, localhost:9096, localhost:9097]
  topics: [tasks]
  consumer_group_id: analytics_group

logger:
  level:  debug

