project:
  name: analytics
  debug: true
  environment: development
  version: 0.1

logger:
  level:  info

rest:
  host: 0.0.0.0
  port: 8080
  debugPort: 8081
  documentation_port: 8082
  gracefulTimeout: 30 # Seconds

grpc:
  host: 0.0.0.0
  port: 5051
  connection_timeout: 10

database:
  type: postgres
  host: localhost
  port: 5432
  user: go_user
  password: 8246go
  db_name: events
